apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-backup-storage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-backup
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 5Gi
