apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: plex
  namespace: media
spec:
  ingressClassName: traefik
  rules:
  - host: plex.lab.emc2.build
    http:
      paths:
      - backend:
          service:
            name: plex
            port:
              number: 32400
        path: /
        pathType: Prefix
