apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrutiny-influxdb-data
  namespace: scrutiny
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rbd-sc
