---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handbrake-config
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]        # CephFS specific
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc       # CephFS specific

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-transcode
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]        # CephFS specific
  resources:
    requests:
      storage: 20Ti
  storageClassName: csi-cephfs-sc       # CephFS specific
