apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  namespace: homelable
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rbd-sc
