---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 8Ti
  storageClassName: csi-cephfs-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cephfs-sc
