apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-library
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
