apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: lidarr
  namespace: media
spec:
  ingressClassName: traefik
  rules:
  - host: lidarr.lab.emc2.build
    http:
      paths:
      - backend:
          service:
            name: lidarr
            port:
              number: 8686
        path: /
        pathType: Prefix
