apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 500Mi
  storageClassName: csi-cephfs-sc
