---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
  labels:
    app: sabnzbd
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      # This DNS config modifies /etc/resolv.conf. Needed so that news.newshosting.com can resolve outside of the cluster,
      # and not get trapped in the wildcard that leads back to lab.emc2.build.
      dnsConfig:
        # nameservers: ["8.8.8.8"]
        options:
          - name: ndots
            value: "2"

      containers:
      - name: sabnzbd
        env:
        - name: PGID
          value: '0'
        - name: PUID
          value: '0'
        - name: TZ
          value: America/Vancouver
        image: lscr.io/linuxserver/sabnzbd:latest
        imagePullPolicy: IfNotPresent
        

        resources:
          limits:
            memory: 4Gi
            cpu: 500m
          requests:
            memory: 2Gi
            cpu: 250m
          
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: pvc-sabnzbd-config
          mountPath: /config
        - name: media-transcode
          mountPath: /transcode
        

          #name: sabnzbd-vol0
        # - mountPath: /downloads
        #   name: sabnzbd-vol1
        # - mountPath: /incomplete-downloads
        #   name: sabnzbd-vol2
        # - mountPath: /watch
        #   name: sabnzbd-vol3
      hostname: sabnzbd
      restartPolicy: Always
      serviceAccountName: ''
      volumes:
      - name: pvc-sabnzbd-config
        persistentVolumeClaim:
          claimName: pv-sabnzbd-config
      - name: media-transcode
        persistentVolumeClaim:
          claimName: media-transcode
      # - hostPath:
      #     path: /mnt/zpool1/apps/media-test/config/sabnzbd
      #     type: Directory
      #   name: sabnzbd-vol0
      # - hostPath:
      #     path: /mnt/zpool1/apps/media-test/download/complete
      #     type: Directory
      #   name: sabnzbd-vol1
      # - hostPath:
      #     path: /mnt/zpool1/apps/media-test/download/incomplete
      #     type: Directory
      #   name: sabnzbd-vol2
      # - hostPath:
      #     path: /mnt/zpool1/apps/media-test/download/watch
      #     type: Directory
      #   name: sabnzbd-vol3
