apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: planka
type: Opaque
stringData:
  POSTGRES_USER: planka
  POSTGRES_PASSWORD: 3jf9a09fa9as9aj3d3f
  POSTGRES_DB: planka
---
apiVersion: v1
kind: Secret
metadata:
  name: planka-secret
  namespace: planka
type: Opaque
stringData:
  # openssl rand -hex 64
  SECRET_KEY: 9e46b60adb4958b66de2e25975857ed603909e325e7b6cba74e1a26a67d9da6457c3f2c864a663a3cd89bac5abe6f54fb10455a6e729ec59d9b765597fbc3098
  DEFAULT_ADMIN_EMAIL: admin@emc2.build
  DEFAULT_ADMIN_PASSWORD: 3jf9a09fa9as9aj3d3f
  DEFAULT_ADMIN_NAME: emcniece
  DEFAULT_ADMIN_USERNAME: emcniece
