apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: immich
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
