apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: immich
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
    CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
