apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: immich
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=  # postgres123 in base64
  POSTGRES_USER: cG9zdGdyZXM=  # postgres in base64
  POSTGRES_DB: aW1taWNo  # immich in base64
