apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: organizr
  namespace: media
spec:
  ingressClassName: traefik
  rules:
  - host: organizr.lab.emc2.build
    http:
      paths:
      - backend:
          service:
            name: organizr
            port:
              number: 80
        path: /
        pathType: Prefix
