apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moneymaker-output
  namespace: moneymaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-rbd-sc
