apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-logs
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcode-cache
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cephfs-sc

