apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: createsleeprepeat-wp
  namespace: createsleeprepeat
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
