apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kdds-mysql
  namespace: kdds
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
