apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echoandflow-wp
  namespace: echoandflow
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
