---
- name: Update repositories cache and install packages
  apt:
    update_cache: yes
    pkg:
    - docker.io
    - docker-compose

- name: Add the runtime user with  a primary group of 'docker'
  user:
    name: '{{ runtime_user }}'
    comment: Ansible managed
    group: docker
    create_home: true
