additionalArguments:
- --api.dashboard=true
- --api.insecure=true
- --providers.kubernetesingress.allowexternalnameservices=true
- --providers.kubernetesingress.allowemptyservices=true
- --providers.kubernetescrd.allowEmptyServices=true
- --log.level=INFO
- --accesslog=true
- --serversTransport.forwardingTimeouts.dialTimeout=3600s
- --serversTransport.forwardingTimeouts.responseHeaderTimeout=3600s
- --serversTransport.forwardingTimeouts.idleConnTimeout=3600s

ports:
  traefik:
    port: 8080
    expose:
      default: true
    exposedPort: 8080
    protocol: TCP
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    respondingTimeouts:
      readTimeout: 3600s
      writeTimeout: 3600s
      idleTimeout: 3600s
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
    respondingTimeouts:
      readTimeout: 3600s
      writeTimeout: 3600s
      idleTimeout: 3600s

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: false

providers:
  kubernetesCRD:
    allowEmptyServices: true
    enabled: true
  kubernetesIngress:
    allowEmptyServices: true
    allowExternalNameServices: true
    enabled: true
    ingressClass: traefik
    publishedService:
      enabled: true

service:
  externalIPs:
  - 192.168.10.91
  type: LoadBalancer
