apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emc2-build-wp
  namespace: emc2-build
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
