---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: emc2-build
  annotations:
    traefik.enable: 'true'
    traefik.frontend.rule: Host:emc2.build
    traefik.port: '80'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.8.3-php8.1-apache
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: mysql-data
              mountPath: /mysql
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WP_REDIS_HOST
              value: localhost 
            - name: WP_REDIS_PORT
              value: "6379"
        - name: redis
          image: redis:3-alpine
          imagePullPolicy: ""
          name: redis
          resources: {}
          ports:
            - containerPort: 6379
              name: redis    
      tolerations:
      - key: "maintenance"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      # This DNS config modifies /etc/resolv.conf. Needed so that external domains can resolve outside of the cluster,
      # and not get trapped in the wildcard that leads back to lab.emc2.build.
      dnsConfig:
        nameservers: ["8.8.8.8", "1.1.1.1"]
        options:
          - name: ndots
            value: "2"
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: emc2-build-wp
        - name: mysql-data
          persistentVolumeClaim:
            claimName: emc2-build-mysql
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
  namespace: emc2-build
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-http-to-https-redirect@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  creationTimestamp: null
  name: emc2-build
  namespace: emc2-build
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - emc2.build
    secretName: emc2-build-letsencrypt-tls
  rules:
  - host: emc2.build
    http:
      paths:
      - backend:
          service:
            name: wordpress-service
            port:
              number: 80
        path: /
        pathType: Prefix
