---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: heimdall
  namespace: default
  labels:
    app: heimdall
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: k3s-04
      containers:
      - name: heimdall
        image: linuxserver/heimdall:latest
        volumeMounts:
        # - name: pvc
        #   mountPath: /config
        - name: cephfs-pvc
          mountPath: /config
      tolerations:
      - key: "maintenance"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      # This DNS config modifies /etc/resolv.conf. Needed so that external domains can resolve outside of the cluster,
      # and not get trapped in the wildcard that leads back to lab.emc2.build.
      dnsConfig:
        # nameservers: ["8.8.8.8"]
        options:
          - name: ndots
            value: "2"

      volumes:
      # - name: pvc
      #   persistentVolumeClaim:
      #     claimName: pv-heimdall-claim
      - name: cephfs-pvc
        persistentVolumeClaim:
          claimName: pv-heimdall-cephfs
