---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]        # CephFS specific
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-cephfs-sc       # CephFS specific
