---
- name: Create app directory
  ansible.builtin.file:
    path: '/home/{{ runtime_user }}/apps/cloudflare-ddns/'
    state: directory

- name: Template docker-compose to ~/apps/
  template:
    src: ../files/docker-compose.yml.j2
    dest: '/home/{{ runtime_user }}/apps/cloudflare-ddns/docker-compose.yml'
    mode: '0644'

- name: Create and start services
  community.docker.docker_compose:
    project_src: '/home/{{ runtime_user }}/apps/cloudflare-ddns'
    state: present
    pull: true
  register: output
